### ISSUE TITLE
希望可以有报错的回复

### ISSUE THREAD

**Issue by SanaChitose** [SonderXiaoming/youzi_voice#1]
测试下来有时候触发了功能，但是没有任何回复，也看不到报错，不知道是哪里出了问题（可能和我服务器在国内有关系？
目前发现如果机器人会复读一次文字内容，则100%可以发送语音，不然都失败
![图片](https://user-images.githubusercontent.com/102790983/185054884-9230e6c5-73d0-4c6d-ad51-295ba018833a.png)
![图片](https://user-images.githubusercontent.com/102790983/185054978-eb259fdc-8fbd-4c21-aae2-43651ee93335.png)

**Comment by SonderXiaoming** [comment]
等等，我还在调试（我还没发社区呢）
（日配也是输入中文，复读其实是翻译）

**Comment by SonderXiaoming** [comment]
你git pull一下看看还会出问题不

**Comment by SanaChitose** [comment]
看到群内大佬在测试，就顺藤摸瓜找过来了（
pull以后基本都有回复了 但是日语会进行奇怪的转译
![图片](https://user-images.githubusercontent.com/102790983/185066385-14d6b9de-8dae-4049-910b-b2948c97714c.png)
![图片](https://user-images.githubusercontent.com/102790983/185066428-362e90f7-daff-4795-a518-a4094286cf5f.png)

**Comment by SonderXiaoming** [comment]
（我本意就是要你输入中文，你的文本是对接自动翻译的）
你看的疑似复读的东西就是翻译（你要考虑很多人日语水平很菜）
应该加一个判断是不是日语
之前谷歌翻译是自动判断的，但你国内用户可能会概率寄，所以git pull之后换成了有道（有道的锅）

**Comment by SanaChitose** [comment]
这个问题看大佬的思路是通过不同的触发指令来解决？如果是柚子日配的话，就没必要走一遍有道的？敬候大佬佳音了

**Comment by SanaChitose** [comment]
其实Google翻译好像是没墙国内（
之前寄可能是其他网站，我可以ping一下

**Comment by SonderXiaoming** [comment]
> 这个问题看大佬的思路是通过不同的触发指令来解决？如果是柚子日配的话，就没必要走一遍有道的？敬候大佬佳音了

难道人均打日文？本来我就是想全中文翻译，中配其实是翻译为片假名，达到好像在说中文的效果。柚子日配也是输入中文

**Comment by SanaChitose** [comment]
啊这 那好吧
