### ISSUE TITLE
安装完以后启动报错

### ISSUE THREAD

**Issue by heyuzhou12345675** [SonderXiaoming/youzi_voice#10]
![image](https://user-images.githubusercontent.com/43637362/189861907-2a80c250-862b-4ae0-93d1-66be2a0a9042.png)
![image](https://user-images.githubusercontent.com/43637362/189862024-cc7d41e0-89d1-43e4-818f-aa179e2c8b89.png)
我理解的是依赖安装的是python2，python3没有安装这个依赖？

**Comment by cpms** [comment]
试一下`pip3 install -r requirements.txt`或者`python3 -m pip install -r requirements.txt`

pip 可以使用参数 -V 来确认对应的 python 版本，如`pip3 -V`

**Comment by heyuzhou12345675** [comment]
好的谢谢，使用pip3 install -r requirements.txt解决这个问题。
然后指令上:角色id列表 命令报错
![image](https://user-images.githubusercontent.com/43637362/190043406-0deab6ff-5f59-4d83-8d08-0de17f684db2.png)

**Comment by SonderXiaoming** [comment]
git pull一下，同意pr时没注意字体被改了

**Comment by heyuzhou12345675** [comment]
拉完还是这个错..
![image](https://user-images.githubusercontent.com/43637362/190047259-41fc9551-424b-4272-8ba0-33987e4ea10b.png)

**Comment by SonderXiaoming** [comment]
linux系的系统？，你create_img.py第52行把simyou.ttf的路径手动输入试试

**Comment by heyuzhou12345675** [comment]
嗯，我直接偷懒改成绝对路径，命令执行成功
