### ISSUE TITLE
转换CQ码 ({"type": "record", "data": {"file": "base64://..... ...转换CQ码 到MiraiGo Element时出现错误

### ISSUE THREAD

**Issue by Mzmba** [SonderXiaoming/youzi_voice#13]
请问这是什么问题，是api错误了吗？
转换CQ码 ({"type": "record", "data": {"file": "base64://SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU5LjMwLjEwMAAAAAAAAAAAAAAA//NwwAAAAAAAAAAAAEluZm......VQ=="}}) 到MiraiGo Element时出现错误: encode silk failed: convert pcm file error: exec: "ffmpeg": executable file not found in $PATH 将忽略本段CQ码.

**Comment by SonderXiaoming** [comment]
你是不是没装ffmpeg

**Comment by Mzmba** [comment]
没看到不好意思，已解决
