### ISSUE TITLE
安装后无反应

### ISSUE THREAD

**Issue by XT-G3** [SonderXiaoming/youzi_voice#16]
我按照步骤安装好之后，发什么指令都没有反应，bot文件里也添加了插件名，想问问有没有什么方法可以知道在哪个环节出了问题？

**Comment by cpms** [comment]
日志呢
先看发送QQ命令的时候有无触发插件指令，如
`[角色语音模仿] INFO: Message xxxxxxxxx triggered voice.`
如果没有，翻到最上面（如果信息太多，重启hoshinobot后查看），看看插件是否有成功加载，没有成功加载一般会有具体的错误信息

**Comment by XT-G3** [comment]
![QQ截图20221014183308](https://user-images.githubusercontent.com/111116375/195826689-2219c751-d5e2-4b3b-82da-80a777d208e2.png)
我比较小白，不是特别看得懂，日志应该是这块了吧，还请教教是什么地方出了问题，谢谢了

**Comment by cpms** [comment]
依赖没安装（或没安装成功），插件没有加载。
在项目目录里重新执行
`python3 -m pip install -i https://mirrors.aliyun.com/pypi/simple/ -r requirements.txt`
注意执行的结果，确认成功安装

**Comment by XT-G3** [comment]
python3的话显示
![QQ截图20221014190130](https://user-images.githubusercontent.com/111116375/195831911-42c8e1ce-949c-4854-a8c3-8bc2ff72bfa3.png)
用python开头的那个的话
![B)5~280KZ{L{%) {ES}8O2J](https://user-images.githubusercontent.com/111116375/195831968-4db15aeb-74f9-44fe-ac94-efb282c8feee.png)
然后还是不行

**Comment by cpms** [comment]
所在的目录不对，不是`HoshinoBot`的目录，而是`youzi_voice`的目录
位于`HoshinoBot/hoshino/modules/youzi_voice/`

或者你试着单独安装ws依赖
`python -m pip install aiowebsocket -i https://mirrors.aliyun.com/pypi/simple/`

**Comment by XT-G3** [comment]
终于有反应了，大佬再帮忙看看，这种情况又该咋解决啊
![QQ截图20221014192105](https://user-images.githubusercontent.com/111116375/195835211-70df7a13-56dd-42d2-860b-3f17fd51bbd4.png)
![QQ截图20221014192037](https://user-images.githubusercontent.com/111116375/195835224-422e824c-0891-40c3-8d11-1cfcfe99a2f8.png)

**Comment by cpms** [comment]
这个大概率是接口又有啥变动，只能等项目作者处理了。

**Comment by XT-G3** [comment]
好的，谢谢大佬
