### ISSUE TITLE
报错aiocqhttp.exceptions.ActionFailed: <ActionFailed data=None, echo={'seq': 95}, msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出'>

### ISSUE THREAD

**Issue by Mirai3rai** [SonderXiaoming/youzi_voice#17]
大佬，我这里只有xcw语音可以使用，其他角色语音统一显示
![image](https://user-images.githubusercontent.com/66004346/195823281-40b263b6-0e24-43f0-aa38-b1452892e166.png)
FFMPEG已安装，aiocqhttp版本为1.4.3，nonebot版本为1.8.4，发送指令后未生成demo.wav，大佬可以帮帮吗
![image](https://user-images.githubusercontent.com/66004346/195824274-3fc35b76-b0ea-46f9-9e2f-959c3481ea81.png)
![image](https://user-images.githubusercontent.com/66004346/195824150-f4e42b5c-a96b-4216-aaa3-d653031741fd.png)

**Comment by cpms** [comment]
估计又是接口有什么变动导致的

**Comment by SonderXiaoming** [comment]
git pull一下即可

**Comment by Mirai3rai** [comment]
好的，感谢大佬

**Comment by Rinco304** [comment]
遇到了相同的问题，好像现在所有的api都不能用了，等大佬更新
