### ISSUE TITLE
语音发不出来 

### ISSUE THREAD

**Issue by howfer** [SonderXiaoming/youzi_voice#2]
![111](https://user-images.githubusercontent.com/35104973/185855310-16d765fc-f93a-478c-883b-2654ac62779b.png)
麻烦作者了

**Comment by SonderXiaoming** [comment]
git pull试一把

**Comment by SonderXiaoming** [comment]
记得检查一下ffmpeg，或者res文件夹下record里面有没有demo.wav

**Comment by howfer** [comment]
感谢回复 已经解决
