### ISSUE TITLE
xcw和派蒙显示错误，然后只有柚子的可以用，其他的用不了

### ISSUE THREAD

**Issue by XT-G3** [SonderXiaoming/youzi_voice#21]
xcw和派蒙显示错误，然后只有柚子的可以用，其他的用不了
![QQ截图20221015145443](https://user-images.githubusercontent.com/111116375/195973742-e9ab0b6f-c5a4-4bb1-90b4-c0ec592e01a2.png)
![QQ截图20221015145825](https://user-images.githubusercontent.com/111116375/195973797-44818200-fb43-4906-9066-dbd714c5fc7e.png)

**Comment by SonderXiaoming** [comment]
其中一个参数改了，这个要打表，过几天修复（等不及可以直接pr）

**Comment by XT-G3** [comment]
> 其中一个参数改了，这个要打表，过几天修复（等不及可以直接pr）

好的，辛苦大佬了

**Comment by SonderXiaoming** [comment]
git pull一下

**Comment by XT-G3** [comment]
> git pull一下

好的，谢谢大佬
