### ISSUE TITLE
2022.10.20号的版本更新后原神语音报错

### ISSUE THREAD

**Issue by SanaChitose** [SonderXiaoming/youzi_voice#24]
如图![图片](https://user-images.githubusercontent.com/102790983/197091066-1f01d388-bfbc-447f-b76f-a5c101772219.png)

**Comment by SonderXiaoming** [comment]
好像是原的api炸了，待我确认确认

**Comment by SonderXiaoming** [comment]
好像没有好的可以白嫖的
