### ISSUE TITLE
超过60字的语音会出错

### ISSUE THREAD

**Issue by joeyHXD** [SonderXiaoming/youzi_voice#29]
ERROR: 'getvoice' object has no attribute 'b_io'
应该是这个错误，大佬能看看吗？
![image](https://user-images.githubusercontent.com/68325229/230571135-f12d7cca-3537-44e5-bc70-3d49ef40046d.png)

**Comment by SonderXiaoming** [comment]
好像是api的字数限制。

**Comment by joeyHXD** [comment]
啊那就没办法惹
