### ISSUE TITLE
网页api改了

### ISSUE THREAD

**Issue by Tamaki-Plus** [SonderXiaoming/youzi_voice#3]
getvoiece.py第十行改为
`speaker_list = ["model0/綾地寧々","model0/因幡めぐる","model0/朝武芳乃","model0/常陸茉子","model0/ムラサメ","model0/鞍馬小春","model0/在原七海"]`

**Comment by SonderXiaoming** [comment]
已修复
看了一下，api好像有更多角色了，近期可能要再改，对多模型的支持
（你如果有能力可以先pr）

**Comment by SonderXiaoming** [comment]
git pull一下试试

**Comment by Rim233** [comment]
api好像又更新了

**Comment by SonderXiaoming** [comment]
？我看看

**Comment by SonderXiaoming** [comment]
https://github.com/Yuri-YuzuChaN/voice
用这个吧，群友改的，比我好多了

**Comment by SonderXiaoming** [comment]
会战暂时没空修了
