### ISSUE TITLE
新增赛马娘模型时遇到了问题

### ISSUE THREAD

**Issue by Rinco304** [SonderXiaoming/youzi_voice#30]
我在试着自己增加赛马娘模型时遇到了
```
[2023-04-07  角色语音模仿] ERROR: 'data'
Traceback (most recent call last):
  File "HoshinoBot\hoshino\msghandler.py", line 23, in handle_message
    await service_func.func(bot, event)
  File "HoshinoBot\hoshino\modules\youzi_voice\__init__.py", line 232, in youzi_voice_ja
    voice = await A.gethash(text_chjp)
  File "HoshinoBot\hoshino\modules\youzi_voice\getvoiece.py", line 78, in gethash
    result = await self.gethash2(text)
  File "HoshinoBot\hoshino\modules\youzi_voice\getvoiece.py", line 135, in gethash2
    self.voicehash = a["output"]["data"][1]
KeyError: 'data'
```
自己排查了一下原因是在`getvoiece.py`文件的`gethash2()`方法中
`a["output"]`里返回的值为`{'error': None}`（其他的都能获取到值但新加的赛马娘一直返回error）
![image](https://user-images.githubusercontent.com/75192177/230636237-694c76d1-54bf-4f81-9888-29fe442b3aeb.png)
![image](https://user-images.githubusercontent.com/75192177/230636397-94772051-b084-4023-90d0-98a5c00de897.png)
但是打印send_data送出的message时发现其内容与网页中发出的message是一致的，网页中成功返回了数据但在这里返回的是error，然后卡这里了不知道怎么解决（本来说没问题就pr的现在尬住了
![image](https://user-images.githubusercontent.com/75192177/230637117-755e7e20-fe87-4017-a8de-26326507473f.png)
我也不太清楚是不是我自己写的有问题，大佬有时间的话可以帮忙看看怎么解决吗，我可以提供自己写的`speaker_dict`与`speaker_id`
注：我把`speaker_id`中部分之前的日文名修改成了中文，赛马娘把罗马音换成了中文（狂暴手打半小时发现最后一个不知道叫啥，乐
以下是我自己新增的部分：
![image](https://user-images.githubusercontent.com/75192177/230637955-a3d5e201-ecf8-4130-bc91-dca1ad4db06e.png)
![image](https://user-images.githubusercontent.com/75192177/230638000-1e2b3d85-b19d-4f0c-babb-27b02ecdc767.png)
![image](https://user-images.githubusercontent.com/75192177/230638070-34a27817-312a-4d90-8379-ca849495e7c2.png)

**Comment by SonderXiaoming** [comment]
你先把这些pr一下，我看看

**Comment by Rinco304** [comment]
> 你先把这些公关一下，我看

#31 
已提交，麻烦大佬了
