### ISSUE TITLE
line119，报错AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by InSnocent** [SonderXiaoming/youzi_voice#4]
![T)UQHCF5Y)JKWS3Q3$%1IKD](https://user-images.githubusercontent.com/25134095/186164057-f736c3b3-5e09-43d9-9c2d-dd6ecf3c1027.png)
OS: Debian GNU/Linux 11 (bullseye) x86_64
服务器位于境外

**Comment by SonderXiaoming** [comment]
这是一直报错还是偶尔报错？

**Comment by SonderXiaoming** [comment]
api好像又改了，我看看

**Comment by SonderXiaoming** [comment]
git pull一下

**Comment by InSnocent** [comment]
没有解决，现在当使用纯日配的时候会返回AttributeError: 'str' object has no attribute 'get'，使用日配或者中配的时候会变成跟issue#2一样的报错_(:з」∠)_

**Comment by SonderXiaoming** [comment]
你纯日配指令是怎么打的

**Comment by SonderXiaoming** [comment]
至于issue2，检查一下ffmpeg，或者res文件夹下record里面有没有demo.wav

**Comment by InSnocent** [comment]
我才发现新机子忘记装ffmpeg了（
感谢

**Comment by SonderXiaoming** [comment]
？都好了

**Comment by InSnocent** [comment]
确实，我觉得你可能把这个提示得写进readme里面（
