### ISSUE TITLE
使用指令:柚子日配 0 我爱宁宁 回复只有翻译文本

### ISSUE THREAD

**Issue by heyuzhou12345675** [SonderXiaoming/youzi_voice#5]
文本会直接发出,过一会儿会报
![$E@ATDL {T} CKJUIN((D)Y](https://user-images.githubusercontent.com/43637362/186321663-5acce4a3-26a9-45cc-858d-f3c217310b61.png)
ffmepg
![~488G PXKBYFGE4RDJ`0`(C](https://user-images.githubusercontent.com/43637362/186322134-9fea8e94-d03b-4011-a77e-5fbba6f0e525.png)
demo.wav
![image](https://user-images.githubusercontent.com/43637362/186322568-516280ba-07e1-447d-96d4-645143739602.png)
代码是今天刚拉的,api是需要翻墙的吗?

**Comment by SonderXiaoming** [comment]
有demo.wav说明已经生成语音，你可以直接听一下
你有没有装过其他语音插件，试着测试一下
可能是你gocq发不出语音（更新一下？）

**Comment by SonderXiaoming** [comment]
gocq是什么报错

**Comment by heyuzhou12345675** [comment]
gocq从0.9.39更新到最新以后可以发送了，谢谢
0.9.39报错是这个
![image](https://user-images.githubusercontent.com/43637362/186337041-66689ff2-1487-4922-b384-1921fb76bd3b.png)

**Comment by SonderXiaoming** [comment]
（这是啥远古版本）这好像是远古版本不用ffmpeg
