### ISSUE TITLE
HoshinoBot和go-cqhttp运行在不同服务器时无法发送语音

### ISSUE THREAD

**Issue by cpms** [SonderXiaoming/youzi_voice#6]
Win服务器上HoshinoBot输出：
![image](https://user-images.githubusercontent.com/4178287/186324162-5f6ad1c9-4b03-457f-a1e3-cce02dcb0f66.png)

Linux服务器上go-cqhttp输出：
`[2022-08-24 11:41:37] [WARNING]: 转换CQ码 ({"type":"record","data":{"file":"file:\/\/\/C:\\Users\\Administrator\\Desktop\\xcwbot\\res\\record\\demo.wav"}}) 到MiraiGo Element时出现错误: open /C:\Users\Administrator\Desktop\xcwbot\res\record\demo.wav: no such file or directory 将忽略本段CQ码. 
[2022-08-24 11:41:37] [WARNING]: 群消息发送失败: 消息为空. `

好像是因为用了file协议发送，文件在go-cqhttp那边不存在所以发送不了。我看了一下go-cqhttp的文档，发送语音的时候好像也支持使用url。不知能不能改成在api获取到语音文件的地址之后就直接传递给go-cqhttp呢。或者转换成base64之后再发送给go-cqhttp。
详见https://docs.go-cqhttp.org/cqcode/#%E8%AF%AD%E9%9F%B3

**Comment by SonderXiaoming** [comment]
我有空看看，不会用base64发送

**Comment by SonderXiaoming** [comment]
git pull一下试试

**Comment by cpms** [comment]
没问题了，感谢
