### ISSUE TITLE
报错AttributeError: 'str' object has no attribute 'get' 且安装了FFmpeg，但是record文件夹内无demo.wav

### ISSUE THREAD

**Issue by ryujou** [SonderXiaoming/youzi_voice#8]

**Comment by SonderXiaoming** [comment]
有没有可能，这些在柚子分类那边

**Comment by ryujou** [comment]
啊这，瞎了。
但是出现了和issue4一样的报错，且安装了FFmpeg，但是record文件夹内无demo.wav
<img width="943" alt="屏幕截图 2022-08-26 103102" src="https://user-images.githubusercontent.com/30500241/186803971-89b12ccd-f4a9-4762-8e97-055883f3744c.png">
<img width="1337" alt="屏幕截图 2022-08-26 103127" src="https://user-images.githubusercontent.com/30500241/186803979-746e2c61-9b63-4c68-bd94-e83bc13068cd.png">

**Comment by SonderXiaoming** [comment]
可能api又改了，我看看

**Comment by SonderXiaoming** [comment]
确实，多了个speed的参数

**Comment by SonderXiaoming** [comment]
git pull

**Comment by ryujou** [comment]
可以了，感谢大佬
