### ISSUE TITLE
api又改了么

### ISSUE THREAD

**Issue by kyokusanaki** [SonderXiaoming/youzi_voice#9]
发现一个很不错的插件，有原神万华镜之类的，望作者君可以整合一下，因为你这边中日双语真挺好

**Comment by SonderXiaoming** [comment]
api改了，而且以我目前水平已经爬不了了，等大佬救，没有就寄

**Comment by SonderXiaoming** [comment]
git pull一下，然后记得装aiowebsocket这个模块，你要的已经整合
